from Palabra import OracionSimple
print ("°|----------------------------------------------------------------------------------|°")
print ("°|                        BIENVENIDO AL ANALIZADOR SINTÁCTICO                       |°")
print ("°|----------------------------------------------------------------------------------|°")
print ("°|         Puede realizar sus oraciones simples con las siguientes palabras         |°")
print ("°|----------------------------------------------------------------------------------|°")
print ("°| PRONOMBRES | DETERMINANTES | PREPOSICIONES | SUSTANTIVOS |  VERBOS   | ADJETIVOS |°")
print ("°|----------------------------------------------------------------------------------|°")
print ("°| Camilo     | Mi            | Con           | Perro       | Ser       | Lento     |°")
print ("°| Evelyn     | Tu            | En            | Cuchillo    | Estar     | Feo       |°")
print ("°| Ana        | El            |               | Gato        | Pelar     | Verde     |°")
print ("°| Juan       | La            |               | Loro        | Comer     | Rapido    |°")
print ("°| Alejandro  | Una           |               | Casa        | Correr    | Grande    |°")
print ("°| Isabel     | Un            |               | Manzana     | Estudiar  | Rica      |°")
print ("°|            |               |               |             | Dormir    | Peligroso |°")
print ("°|            |               |               |             | Programar | Sucia     |°")
print ("°|            |               |               |             | Enseñar   |           |°")
print ("°|            |               |               |             | Aprender  |           |°")
print ("°|----------------------------------------------------------------------------------|°")
print ("°|                                     RECUERDE                                     |°")
print ("°|----------------------------------------------------------------------------------|°")
print ("°| *La oración debe tener exactamente un verbo                                      |°")
print ("°| *La oración debe tener como mínimo dos palabras y como máximo seis               |°")
print ("°| *Los verbos solo pueden conjugarse en presente o en pasado                       |°")
print ("°| *Si el verbo se conjuga en pasado, debe llevar su respectiva tilde               |°")
print ("°|----------------------------------------------------------------------------------|°")
print ("°|----------------------------------------------------------------------------------|°")
print ("°|                                     EJEMPLOS                                     |°")
print ("°|----------------------------------------------------------------------------------|°")
print ("°| *Camilo estudió en una casa verde                                                |°")
print ("°| *Evelyn programa rapido en la casa                                               |°")
print ("°| *El perro comió con el gato                                                      |°")
print ("°| *La manzana verde es rica                                                        |°")
print ("°|----------------------------------------------------------------------------------|°\n")
Flag = True
while Flag:
    Opcion= input("¿Desea ingresar una nueva oración? (Si/No): ").lower()
    if (Opcion=="si"):
        Palabra=input("Ingrese su oración: ")
        Oracion1 = OracionSimple(Palabra)
        Oracion1.Validar()
    else:
        Flag=False
        print ("\n°|----------------------------------------------------------------------------------|°")
        print ("°|                    GRACIAS POR USAR EL ANALIZADOR SINTÁCTICO                     |°")
        print ("°|----------------------------------------------------------------------------------|°")
